elections/urls.py
from django.urls import path
from . import views

app_name='elections'
urlpatterns = [
    path('messages-list',views.messages_list,name='messages_list'),
    path('messages-view/<int:id>/<int:init_id>/<str:page_type>',views.messages_view,name='messages_view'), 
    path('message-campaign', views.message_campaign, name='message_campaign'),
    path('list-elections', views.list_elections, name='list_elections'),
    path('add-elections', views.add_elections, name='add_elections'),
    path('delete-election/<int:id>', views.delete_election, name='delete_election'),    
    path('edit-elections/<int:id>', views.edit_elections, name='edit_elections'),  
    path('list-election-candidates/<int:id>',views.list_election_candidates, name='list_election_candidates'), 
    path('view-election-candidates/<int:id>/<int:id_2>',views.view_election_candidates, name='view_election_candidates'),   
    path('add-election-candidates/<int:id>/<int:id_2>',views.add_election_candidates, name='add_election_candidates'),
    path('election-parties/<int:id>', views.election_parties_v, name='election_parties'),  
    path('election-position/<int:id>', views.election_position_v, name='election_position'),
    path('election-parties-delete/<int:id>/<int:edit_id>', views.election_parties_delete, name='election_parties_delete'),  
    path('election-position-delete/<int:id>/<int:edit_id> ', views.election_position_delete, name='election_position_delete'),               
    path('delete-election-candidates/<int:id>/<int:id_2>',views.delete_election_candidates, name='delete_election_candidates'),            
]

evoting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin2023/', admin.site.urls),
    path('',include('home.urls',namespace='home'),),        
    path('candidates/',include('candidates.urls',namespace='candidates'),),
    path('election-officers/',include('election_officers.urls',namespace='election_officers'),),
    path('voters/',include('voters.urls',namespace='voters'),), 
    path('elections/',include('elections.urls',namespace='elections')),             
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns = [
    path('',views.home,name='home'),
    path('home',views.home,name='home'),
    path('about-us',views.about_us,name='about_us'),
    path('contact-us',views.contact_us,name='contact_us'),
    path('list-elections',views.list_elections,name='list_elections'),
    path('view-elections',views.view_elections,name='view_elections'),    
    path('list-results',views.list_results,name='list_results'),
    path('view-results/<int:id>',views.view_results,name='view_results'),         
]

elections/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from .models import *
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse
from django.conf import settings
import base64, random
from Crypto.Cipher import AES
from Crypto.Util.Padding import pad, unpad

# Define the AES256 encryption and decryption functions
def encrypt_AES256(plaintext):
    key = settings.SECRET_KEY
    iv = b'1234567890123456' # Initialization vector
    cipher = AES.new(key, AES.MODE_CBC, iv)
    ciphertext = cipher.encrypt(pad(plaintext.encode(), AES.block_size))
    return base64.b64encode(ciphertext).decode()

def decrypt_AES256(ciphertext):
    key = settings.SECRET_KEY
    iv = b'1234567890123456' # Initialization vector
    ciphertext = base64.b64decode(ciphertext.encode())
    cipher = AES.new(key, AES.MODE_CBC, iv)
    plaintext = unpad(cipher.decrypt(ciphertext), AES.block_size)
    return plaintext.decode()

def messages_list(request):
    user_messages_list = messages_index.objects.filter(sender_user_id=request.session['user_id']).all()
    user_messages_list_2 = messages_index.objects.filter(recipient_user_id=request.session['user_id']).all()
    user_messages_list_array = []
    if user_messages_list.count() > 0:
        for row in user_messages_list:
            user_messages_list_array.append({ 'messages_index': row, 'msg_type':'sender' }) 

    if user_messages_list_2.count() > 0:
        for row in user_messages_list_2:
            user_messages_list_array.append({ 'messages_index': row, 'msg_type':'recipient' }) 

    context = { 'user_messages_list_array':user_messages_list_array }
    return render(request, 'elections/list-message.html', context)     

def messages_view(request, id, init_id, page_type):
    if page_type == 'list':

        try:
            msg_index_data = messages_index.objects.get(unique_id=id)
        except messages_index.DoesNotExist:
            msg_index_data = None

        if msg_index_data is not None:         
            msg_contain = messages_contain.objects.filter(msg_index=msg_index_data)
            if msg_index_data.sender_user_id == request.session['user_id']:
                userdata = user_registration.objects.get(unique_id=msg_index_data.recipient_user_id)  
            else:
                userdata = user_registration.objects.get(unique_id=msg_index_data.sender_user_id)        
        else:
                msg_contain = ''
                userdata = ''
    else:
        
        userdata = user_registration.objects.get(unique_id=init_id)    
        try:
            msg_index_data = messages_index.objects.get(recipient_user_id=init_id, sender_user_id=request.session['user_id'])
        except messages_index.DoesNotExist:
            msg_index_data = None

        if msg_index_data is not None:         
            msg_contain = messages_contain.objects.filter(msg_index=msg_index_data)
        else:
            msg_contain = ''       

    if request.method == 'POST':
        data_record = request.POST

        if msg_index_data is not None:           
            messages_data =  messages_contain(
            msg_index = msg_index_data,
            participant_user_id = request.session['user_id'],
            messages_text = data_record['message'],
            )              
            messages_data.save()
        else: 
            messages_list_data = messages_index(
            recipient_user_id = init_id,
            sender_user_id = request.session['user_id'],
            )
            messages_list_data.save()
            latest_msg_index = messages_index.objects.latest('unique_id')

            messages_data =  messages_contain(
            msg_index = latest_msg_index,
            participant_user_id = request.session['user_id'],
            messages_text = data_record['message'],
            )              
            messages_data.save()
        return redirect(reverse('elections:messages_view', kwargs={'id': id, 'init_id':init_id, 'page_type':page_type, }))

    context = { 'userdata': userdata, 'user_messages':msg_contain }
    return render(request, 'elections/view-message.html', context)         

def message_campaign(request):
    if request.method == 'POST':
        data_record = request.POST
        list_voters = user_registration.objects.filter(user_type='voters').all()
        if list_voters.count() > 0:
            for row in list_voters:
                sender_id = row.unique_id  

                try:
                    msg_index_data = messages_index.objects.get(recipient_user_id=sender_id, sender_user_id=request.session['user_id'])
                except messages_index.DoesNotExist:
                    msg_index_data = None                    

                if msg_index_data is not None:           
                    messages_data =  messages_contain(
                    msg_index = msg_index_data,
                    participant_user_id = request.session['user_id'],
                    messages_text = data_record['message'],
                    message_type = 'campaign',
                    )              
                    messages_data.save()
                else: 
                    messages_list_data = messages_index(
                    recipient_user_id = sender_id,
                    sender_user_id = request.session['user_id'],
                    )
                    messages_list_data.save()
                    latest_msg_index = messages_index.objects.latest('unique_id')

                    messages_data =  messages_contain(
                    msg_index = latest_msg_index,
                    participant_user_id = request.session['user_id'],
                    messages_text = data_record['message'],
                    message_type = 'campaign',
                    )              
                    messages_data.save()    
    context = { 'userdata': user_registration.objects.get(unique_id=request.session['user_id']) }
    return render(request, 'elections/message-campaign.html', context)

def list_elections(request):
    context = { 'list_electiondata': elections.objects.filter(election_officers_id=request.session['user_id']) }
    return render(request, 'elections/list-elections.html', context) 

def add_elections(request):
    if request.method == 'POST':
        data_record = request.POST
        logo_image_t = request.FILES['logo_image']
        folder = 'elections' # subfolder name
        fs = FileSystemStorage(location=f'media/{folder}')
        file_name = fs.save(logo_image_t.name, logo_image_t)
        signup = elections(
            election_officers=user_registration.objects.get(unique_id=request.session['user_id']),
            title=data_record['title'],
            description=data_record['description'],
            logo_image=f'{folder}/{file_name}',
            election_start_date_time=data_record['start_date'],
            election_end_date_time=data_record['end_date'],
            #status=data_record['status'],
            status='pending',
        )            
        signup.save()
        last_insert_id = signup.unique_id
        messages.success(request, 'Successfully added the election! Please proceed to provide further details.')
        return redirect(reverse('elections:edit_elections', kwargs={'id': last_insert_id}))         
    context = {}
    return render(request, 'elections/add-elections.html', context)

def edit_elections(request, id):
    userdata = elections.objects.get(unique_id=id)
    userdata_party = election_parties.objects.filter(elections=userdata)
    userdata_position = election_position.objects.filter(elections=userdata)
    userdata_candidates = election_candidates.objects.filter(elections=userdata,status='accepted')
    userdata_voting = election_votes.objects.filter(elections=userdata)
    if request.method == 'POST':
        data_record = request.POST
#   Status working here
        status = 'pending'
        if data_record['status']=="active":
                status = 'active'
                if userdata_party.count() == 0:
                    status = 'pending'
                    messages.info(request, 'Please add atleast a party to mark this election active')
                elif userdata_position.count() == 0:
                    status = 'pending'
                    messages.info(request, 'Please add atleast a position to mark this election active')                
        elif data_record['status']=="ready":
                status = 'ready'
                if userdata_party.count() == 0:
                    status = 'pending'
                    messages.info(request, 'Please add atleast a party to mark this election completed and ready for voting')
                elif userdata_position.count() == 0:
                    status = 'pending'
                    messages.info(request, 'Please add atleast a position to mark this election completed and ready for voting')            
                elif userdata_candidates.count() == 0:
                    status = 'active' 
                    messages.info(request, 'To mark this election ready for voting, Please ensure that at least one candidate has been added and their status has been accepted by the election officials.')  
        elif data_record['status']=="completed":
                status = 'completed'
                if userdata.status == 'published':
                    messages.info(request, 'If you change the status back to "completed," the election results will not be published anymore!')
                    status = 'completed'  
                elif userdata.status == 'ready':
                    messages.info(request, 'This marks the election completed nad public wont be able to vote anymore!')
                    status = 'completed'
                else:
                    status = userdata.status
        elif data_record['status']=="published":
            status = "published"

templates/elections/edit-elections.html
{% extends 'layout.html' %}
{% block title %}
eVoting
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
<link href="{% static 'plugins/datatables/datatables.min.css' %}" rel="stylesheet"/>
{% endblock %}
<!-- custom css end-->
{% block content %}
<section class="page-title">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-md-2 text-center">
				<!-- Title text -->
			</div>
		</div>
	</div>
	<!-- Container End -->
</section>
<section class="advt-post bg-gray py-2">
	<div class="row">
		<div class="col-md-12 text-center">
			{% if messages %}
			<ul class="messages text-center">
			{% for message in messages %}
			 <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
			 {% endfor %}
			 </ul>
			 {% endif %}
		</div>
	</div>
	<div class="container">

		<div class="row">
			<div class="col-md-12">
			  <a href="{% url 'elections:list_elections' %}" class="btn btn-danger btn-sm pull-right" style="padding: .25rem .5rem;"><i class="fa fa-arrow-left"></i> Back</a>
			</div>
		  </div>
		  <br />

	  <form action="" method="POST" id="myform" method="post" role="form" enctype="multipart/form-data" >
		{% csrf_token %}
		<!-- Post Your ad start -->
		<fieldset class="border border-gary px-3 px-md-4 py-4 mb-5">
		  <div class="row">
			<div class="col-lg-12">
			  <h3>Edit Elections</h3>
			</div>
			<div class="col-lg-6">
			  <h6 class="font-weight-bold pt-4 pb-1">Title Of Election:</h6>
			  <input type="text" name="title" id="title" class="form-control bg-white" placeholder="Election title go here" value="{{ userdata.title }}"  >
			  <h6 class="font-weight-bold pt-4 pb-1">Start Date/Time:</h6>
			  <div class="row px-3">
				  <div class="col-lg-8 rounded my-2 px-0">
					<input type="datetime-local" name="start_date" id="start_date" class="form-control bg-white" placeholder="Start Date" value="{{ userdata.election_start_date_time|date:'Y-m-d\TH:i' }}">
				  </div>
			  </div>
			  <h6 class="font-weight-bold pt-4 pb-1">Description:</h6>
			  <textarea name="description" id="description" class="form-control bg-white" rows="7" placeholder="Write details about this election">{{ userdata.description }}</textarea>
			</div>
			<div class="col-lg-6">
			  <h6 class="font-weight-bold pt-4 pb-1">Select Status:</h6>
			  <select name="status" id="status" class="form-control w-100 bg-white">
				<option value="pending" {% if userdata.status == 'pending' %} selected {% endif %} >Pending (Default Status)</option>
				<option value="active" {% if userdata.status == 'active' %} selected {% endif %} >Active (After adding Party and Position)</option>
				<option value="ready" {% if userdata.status == 'ready' %} selected {% endif %} >Ready (Ready for Election )</option>
				<option value="completed" {% if userdata.status == 'completed' %} selected {% endif %} >Completed (Election Completed)</option>				
				<option value="published" {% if userdata.status == 'published' %} selected {% endif %} >Publish (Results Published)</option>
			  </select>
			  <div class="price">
				<h6 class="font-weight-bold pt-4 pb-1">End Date/Time:</h6>
				<div class="row px-3">
				  <div class="col-lg-8 rounded my-2 px-0">
					<input type="datetime-local" name="end_date" id="end_date" class="form-control bg-white" placeholder="End Date" value="{{ userdata.election_end_date_time|date:'Y-m-d\TH:i' }}" >
				  </div>
				</div>
			  </div>
			</div>
		  </div>
		  <button type="submit" class="btn btn-primary d-block mt-2">Submit</button>
		</fieldset>		
	  </form>
	</div>
</section>
<section class="advt-post py-2">
	<div class="container">
	  <form action="{% url 'elections:election_parties' id=edit_id %}" method="POST" id="myform1" role="form" enctype="multipart/form-data" >
		{% csrf_token %}
		<!-- Post Your ad start -->
		<fieldset class="border border-gary px-3 px-md-4 py-4 mb-5">
		  <div class="row">
			<div class="col-lg-12">
			  <h3>Add Recognized National Parties</h3>
			</div>
			<div class="col-lg-5">
			  <h6 class="font-weight-bold pt-4 pb-1">Party Name:</h6>
			  <input type="text" name="party_name" id="party_name" class="form-control bg-white" placeholder="Party name goes here" value="">
			  <h6 class="font-weight-bold pt-4 pb-1">Upload party image:</h6>
			  <div class="form-group choose-file d-inline-flex">
				<i class="fa fa-user text-center px-3 pt-2"></i>
				<input type="file" class="form-control-file" name="party_image" id="party_iamge" >
			 </div>
			 <div class="error" id="party_image_error" ></div>
			  <h6 class="font-weight-bold pt-4 pb-1">Tag line:</h6>
			  <textarea name="tag_line" id="tag_line" class="form-control bg-white" rows="2" placeholder="Write a tag line about this election"></textarea>
			  <button type="submit" class="btn btn-primary d-block mt-2">Submit</button>			  
			</div>
			<div class="col-lg-7">
				{% if list_party %}
                <table class="table table-bordered bordered table-striped table-condensed datatable custom-table" id="data_table_1" >
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>Party Image</th>
                        <th>Name</th>
                        <th>tagline</th>
                        <th class="text-center">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for row in list_party %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td class="product-thumb">
                          <img src="{{ row.party_image.url }}" height="50" alt="image description" class="avatar" >
                        </td>
                        <td class="product-details">
                          <span class="add-id"><strong>{{ row.party_name }}</strong></span>  <br />                      
                        </td>
                        <td class="product-category"><span class="categories">{{ row.tag_line }}</span></td>  
                        <td class="action" data-title="Action">
                          <div class="">
                            <ul class="list-inline justify-content-center">
                              <li class="list-inline-item">
                                <a onclick="return confirm('Are you sure you want to delete this item?');" data-toggle="tooltip" data-placement="top" title="view" class="view" href="{% url 'elections:election_parties_delete' id=row.unique_id edit_id=edit_id %}">
                                  <i class="fa fa-minus"></i>
                                </a>
                              </li>
                            </ul>
                          </div>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  {% else %}
                  <p><b style="color: brown" >No parties found.</b></p>
                  {% endif %}
			</div>
		  </div>
		</fieldset>
	  </form>
	</div>
</section>
<section class="advt-post bg-gray py-2">
	<div class="container">
	  <form action="{% url 'elections:election_position' id=edit_id %}" method="POST" id="myform2" role="form">
		{% csrf_token %}
		<!-- Post Your ad start -->
		<fieldset class="border border-gary px-3 px-md-4 py-4 mb-5">
		  <div class="row">
			<div class="col-lg-12">
			  <h3>Add Postions</h3>
			</div>
			<div class="col-lg-5">
			  <h6 class="font-weight-bold pt-4 pb-1">Position Name:</h6>
			  <input type="text" name="position_name" id="position_name" class="form-control bg-white" placeholder="Position name goes here" value="">
			  <h6 class="font-weight-bold pt-4 pb-1">Tag line:</h6>
			  <textarea name="tag_line_2" id="tag_line_2" class="form-control bg-white" rows="2" placeholder="Write a tag line about this election"></textarea>
			  <button type="submit" class="btn btn-primary d-block mt-2">Submit</button>			  
			</div>
			<div class="col-lg-7">
				{% if list_position %}
                <table class="table table-bordered bordered table-striped table-condensed datatable custom-table" id="data_table_2" >
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>tagline</th>
                        <th class="text-center">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for row in list_position %}
                      <tr>
                        <td>{{ forloop.counter }}</td>                    
                        <td class="product-details">
                          <span class="add-id"><strong>{{ row.postion_name }}</strong></span>  <br />                      
                        </td>
                        <td class="product-category"><span class="categories">{{ row.tag_line }}</span></td>  
                        <td class="action" data-title="Action">
                          <div class="">
                            <ul class="list-inline justify-content-center">
                              <li class="list-inline-item">
                                <a onclick="return confirm('Are you sure you want to delete this item?');" data-toggle="tooltip" data-placement="top" title="view" class="view" href="{% url 'elections:election_position_delete' id=row.unique_id edit_id=edit_id %}">
                                  <i class="fa fa-minus"></i>
                                </a>
                              </li>
                            </ul>
                          </div>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  {% else %}
                  <p style="color: brown"><b>No position found.</b></p>
                  {% endif %}
			</div>
		  </div>
		</fieldset>
	  </form>
	</div>
</section>
{% endblock %}
<!-- custom js -->
{% block js %}
<script src="{% static 'plugins/datatables/datatables.min.js' %}"></script>
<script src="{% static 'plugins/jquery-validate/jquery.validate.min.js' %}" defer></script>
<script src="{% static 'plugins/jquery-validate/additional-methods.min.js' %}" defer></script>
<script>
$(document).ready(function() {

 $('#data_table_1').DataTable();
 $('#data_table_2').DataTable();

  // Add validation rules and messages
  $("#myform").validate({
    rules: {
	title: {
        required: true,
		minlength: 10,
		maxlength: 500,
      },
      start_date: {
        required: true,
		dateGreaterThanOrEqual: new Date() 
      },
	  end_date: {
        required: true,
		greaterThan: "#start_date",
		dateGreaterThanOrEqual: new Date() 
      },
      description: {
        required: true
      },
      status: {
        required: true
      },
    },
    messages: {
	title: {
        required: "Please enter the title of the election."
      },
      start_date: {
        required: "Please select the start date/time of the election."
      },
	  end_date: {
        required: "Please select the end date/time of the election.",
		greaterThan: "The end date must be greater than the start date.",
		dateGreaterThanOrEqual: "Please specify a valid date."
      },
      description: {
        required: "Please enter a description for the election."
      },
      status: {
        required: "Please select the status of the election."
      },
      /* logo_image: {
        required: "Please select a logo for the election."
      } */
    }
  });
  $.validator.addMethod("greaterThan", function(value, element, param) {
        return new Date(value) > new Date($(param).val());
      }, "Please specify a valid date.");
//   $.validator.addMethod("dateGreaterThanOrEqual", function(value, element, param) {
//     // Convert the date values to Date objects and compare them with today's date
//     return new Date(value) >= param;
//   }, "Please specify a valid date that is greater than or equal to today's date.");

  $("#myform1").validate({
		// specify the rules for each input field
		rules: {
		  party_name: {
			required: true,
			minlength: 3
		  },
		  party_image: {
			required: true,
			accept: "image/*"
		  },
		  tag_line: {
			required: true,
			minlength: 10
		  }
		},
		// specify the error messages
		messages: {
		  party_name: {
			required: "Please enter the party name",
			minlength: "Party name must be at least 3 characters long"
		  },
		  party_image: {
			required: "Please select a profile photo",
			accept: "Only image files are allowed"
		  },
		  tag_line: {
			required: "Please enter a tag line",
			minlength: "Tag line must be at least 10 characters long"
		  }
		},
		errorPlacement: function(error, element) {
      if (element.attr('name') == 'party_image') {
        error.insertAfter('#party_image_error'); // specify the ID of the error container
      } else {
        error.insertAfter(element);
      }
    }
	  });

	  $("#myform2").validate({
		// specify the rules for each input field
		rules: {
			position_name: {
			required: true,
			minlength: 3
		  },
		  tag_line_2: {
			required: true,
			minlength: 10
		  }
		},
		// specify the error messages
		messages: {
			position_name: {
			required: "Please enter the position name",
			minlength: "Party name must be at least 3 characters long"
		  },
		  tag_line_2: {
			required: "Please enter a tag line",
			minlength: "Tag line must be at least 10 characters long"
		  }
		}
	  });	  
});
</script>
{% endblock %}
<!-- custom js end-->

templates/elections/list-election-candidates.html
{% extends 'layout.html' %}
{% block title %}
eVoting
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
<link href="{% static 'plugins/datatables/datatables.min.css' %}" rel="stylesheet"/>
{% endblock %}
<!-- custom css end-->
{% block content %}
<section class="page-title">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-md-2 text-center">
				<!-- Title text -->
			</div>
		</div>
	</div>
	<!-- Container End -->
</section>
<section class="dashboard section">
	<div class="row">
		<div class="col-md-12">
		  <div class="section-title">
			<h2>Election Candidates</h2>
		  </div>
		</div>
	  </div>
	<div class="row">
		<div class="col-md-12 text-center">
			{% if messages %}
			<ul class="messages text-center">
			{% for message in messages %}
			 <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
			 {% endfor %}
			 </ul>
			 {% endif %}
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
			  <a href="{% url 'elections:list_elections' %}" class="btn btn-danger btn-sm pull-right" style="padding: .25rem .5rem;"><i class="fa fa-arrow-left"></i> Back</a>
			</div>
		  </div>
		  <br />
		<!-- Post Your ad start -->
		<fieldset class="">
		  <div class="row">
			<div class="col-lg-12">
				<h6 class="font-weight-bold pb-1">Added Candidates:</h6>
				{% if userdata_candidates_election %}
				<table class="table table-bordered bordered table-striped table-condensed datatable custom-table" id="example1" >
					<thead>
					  <tr>
						<th>#</th>
						<th>Photo</th>
						<th>Name</th>
						<th>Status</th>
						<th>Party</th>
						<th>Position</th>
						<th class="text-center">Action</th>
					  </tr>
					</thead>
					<tbody>
						{% for row in userdata_candidates_election %}
					  <tr>
						<td>{{ forloop.counter }}</td>
						<td class="product-thumb">
						  <img src="{{ row.candidates.profile_photo.url }}" height="100" alt="image description" class="avatar" >
						</td>
						<td class="product-details">
						  <h3 class="title">{{ row.candidates.first_name }} {{ row.candidates.last_name }}</h3>
						  <span class="add-id"><strong>Aadhaar ID:</strong> {{ row.candidates.aadhaar_number }}</span>  <br />
						  <span class="location"><strong>Email:</strong> {{ row.candidates.email_address }}</span>
						  <span class="location"><strong>Mobile:</strong> {{ row.candidates.mobile_number }}</span>                      
						</td>
						<td>	
							{% if row.status == 'accepted' %}
							<b style="color: green;">Accepted</b>
							{% elif row.status == 'rejected' %}
							<b style="color: red;">Rejected</b>
							{% else %}
							<b style="color: blue;">Applied</b>
							{% endif %}  						
						</td>
						<td>
							<span class="location"><img src="{{ row.party.party_image.url }}" height="100" alt="image description" class="avatar" ></span>
							<span class="location"> {{ row.party.party_name }}</span>    
						</td>
						<td>{{ row.position.postion_name }}</td>
						<td class="action" data-title="Action">
						  <div class="">
							<ul class="list-inline justify-content-center">

							  <li class="list-inline-item">
                                <a data-toggle="tooltip" data-placement="top" title="view" class="view" href="{% url 'elections:view_election_candidates' id=userdata.unique_id id_2=row.unique_id %}">
                                  <i class="fa fa-eye"></i>
                                </a>
                              </li>

							  <li class="list-inline-item">					
								<a data-toggle="tooltip" data-placement="top" title="view" class="view" href="{% url 'elections:delete_election_candidates' id=userdata.unique_id id_2=row.unique_id %}">
								  <i class="fa fa-trash"></i>
								</a>
							  </li>

							</ul>
						  </div>
						</td>
					  </tr>
					  {% endfor %}
					</tbody>
				  </table>
				  {% else %}
				  <p><b>No Candidates found.</b></p>
				  {% endif %}				
			</div>
			</div>
		  </div>
		</fieldset>
		<!-- Post Your ad end -->
	</div>
  </section>
{% endblock %}
<!-- custom js -->
{% block js %}
<script src="{% static 'plugins/datatables/datatables.min.js' %}"></script>
<script>
$(document).ready(function () {
    $('#example').DataTable();
	$('#example1').DataTable();
});  
</script>
{% endblock %}
<!-- custom js end-->