candidates/urls.py
from django.urls import path
from . import views

app_name='candidates'
urlpatterns = [
    path('',views.sign_in,name='sign_in'),    
    path('sign-in',views.sign_in,name='sign_in'),
    path('sign-up',views.sign_up,name='sign_up'),
    path('sign-up-otp/<int:id>',views.sign_up_otp,name='sign_up_otp'),    
    path('signup-check-email',views.signup_check_email,name='signup_check_email'),
    path('signup-check-mobile',views.signup_check_mobile,name='signup_check_mobile'),
    path('signup-check-aadhaar',views.signup_check_aadhaar,name='signup_check_aadhaar'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('edit-profile', views.edit_profile, name='edit_profile'), 
    path('edit-profile-pic', views.edit_profile_pic, name='edit_profile_pic'),
    path('edit-profile-password', views.edit_profile_password, name='edit_profile_password'), 
    path('list-voters', views.list_voters, name='list_voters'),
    path('view-voters/<int:id>', views.view_voters, name='view_voters'),        
    path('list-elections', views.list_elections, name='list_elections'),
    path('view-elections/<int:id>', views.view_elections, name='view_elections'),
    path('delete-elections/<int:id>/<int:id2>', views.delete_elections, name='delete_elections'),    
    path('apply-election-party/<int:id>/<int:party_id>',views.apply_election_party, name='apply_election_party'), 
    path('apply-election-position/<int:id>/<int:position_id>',views.apply_election_position, name='apply_election_position'),         
    path('edit-elections/<int:id>', views.edit_elections, name='edit_elections'),
    path('logout', views.logout, name='logout'),   
]

election_officers/urls.py
from django.urls import path
from . import views

app_name='election_officers'
urlpatterns = [
    path('',views.sign_in,name='sign_in'),    
    path('sign-in',views.sign_in,name='sign_in'),
    path('sign-up',views.sign_up,name='sign_up'),
    path('sign-up-otp/<int:id>',views.sign_up_otp,name='sign_up_otp'),    
    path('signup-check-email',views.signup_check_email,name='signup_check_email'),
    path('signup-check-mobile',views.signup_check_mobile,name='signup_check_mobile'),
    path('signup-check-aadhaar',views.signup_check_aadhaar,name='signup_check_aadhaar'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('edit-profile', views.edit_profile, name='edit_profile'), 
    path('edit-profile-pic', views.edit_profile_pic, name='edit_profile_pic'),
    path('edit-profile-password', views.edit_profile_password, name='edit_profile_password'), 
    path('list-candidates', views.list_candidates, name='list_candidates'), 
    path('list-voters', views.list_voters, name='list_voters'), 
    path('view-candidates/<int:id>', views.view_candidates, name='view_candidates'),
    path('view-voters/<int:id>', views.view_voters, name='view_voters'),
    path('change-user-status/<int:id>', views.change_user_status, name='change_user_status'),
    path('logout', views.logout, name='logout'),   
]

elections/urls.py
from django.urls import path
from . import views

app_name='elections'
urlpatterns = [
    path('messages-list',views.messages_list,name='messages_list'),
    path('messages-view/<int:id>/<int:init_id>/<str:page_type>',views.messages_view,name='messages_view'), 
    path('message-campaign', views.message_campaign, name='message_campaign'),
    path('list-elections', views.list_elections, name='list_elections'),
    path('add-elections', views.add_elections, name='add_elections'),
    path('delete-election/<int:id>', views.delete_election, name='delete_election'),    
    path('edit-elections/<int:id>', views.edit_elections, name='edit_elections'),  
    path('list-election-candidates/<int:id>',views.list_election_candidates, name='list_election_candidates'), 
    path('view-election-candidates/<int:id>/<int:id_2>',views.view_election_candidates, name='view_election_candidates'),   
    path('add-election-candidates/<int:id>/<int:id_2>',views.add_election_candidates, name='add_election_candidates'),
    path('election-parties/<int:id>', views.election_parties_v, name='election_parties'),  
    path('election-position/<int:id>', views.election_position_v, name='election_position'),
    path('election-parties-delete/<int:id>/<int:edit_id>', views.election_parties_delete, name='election_parties_delete'),  
    path('election-position-delete/<int:id>/<int:edit_id> ', views.election_position_delete, name='election_position_delete'),               
    path('delete-election-candidates/<int:id>/<int:id_2>',views.delete_election_candidates, name='delete_election_candidates'),            
]

evoting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin2023/', admin.site.urls),
    path('',include('home.urls',namespace='home'),),        
    path('candidates/',include('candidates.urls',namespace='candidates'),),
    path('election-officers/',include('election_officers.urls',namespace='election_officers'),),
    path('voters/',include('voters.urls',namespace='voters'),), 
    path('elections/',include('elections.urls',namespace='elections')),             
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns = [
    path('',views.home,name='home'),
    path('home',views.home,name='home'),
    path('about-us',views.about_us,name='about_us'),
    path('contact-us',views.contact_us,name='contact_us'),
    path('list-elections',views.list_elections,name='list_elections'),
    path('view-elections',views.view_elections,name='view_elections'),    
    path('list-results',views.list_results,name='list_results'),
    path('view-results/<int:id>',views.view_results,name='view_results'),         
]

voters/urls.py
from django.urls import path
from . import views

app_name='voters'
urlpatterns = [
    path('',views.sign_in,name='sign_in'),    
    path('sign-in',views.sign_in,name='sign_in'),
    path('sign-up',views.sign_up,name='sign_up'),
    path('sign-up-otp/<int:id>',views.sign_up_otp,name='sign_up_otp'),    
    path('signup-check-email',views.signup_check_email,name='signup_check_email'),
    path('signup-check-mobile',views.signup_check_mobile,name='signup_check_mobile'),
    path('signup-check-aadhaar',views.signup_check_aadhaar,name='signup_check_aadhaar'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('edit-profile', views.edit_profile, name='edit_profile'), 
    path('edit-profile-pic', views.edit_profile_pic, name='edit_profile_pic'),
    path('edit-profile-password', views.edit_profile_password, name='edit_profile_password'),
    path('list-elections', views.list_elections, name='list_elections'),
    path('before-elections/<int:id>', views.before_elections, name='before_elections'),
    path('before-elections-otp/<int:id>/<str:aadhaar_id>', views.before_elections_otp, name='before_elections_otp'),    
    path('view-elections/<int:id>/<str:aadhaar_id>', views.view_elections, name='view_elections'),
    path('view-elections-completed/<int:id>/<str:aadhaar_id>', views.view_elections_completed, name='view_elections_completed'),       
    path('logout', views.logout, name='logout'),   
]

templates/includes/footer.html
{% load static %}
<footer class="footer section section-sm">
  <!-- Container Start -->
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-7 offset-md-1 offset-lg-0 mb-4 mb-lg-0">
        <!-- About -->
        <div class="block about">
          <!-- footer logo -->
          <img src=" {% static 'images/logo-footer.png' %}" alt="logo">
          <!-- description -->
          <p class="alt-color">The Electronic Voting System is a state-of-the-art online platform that facilitates secure and transparent
            elections for various organizations, such as businesses, governments, and non-profit organizations.</p>
        </div>
      </div>
      <!-- Link list -->
      <div class="col-lg-2 offset-lg-1 col-md-3 col-6 mb-4 mb-lg-0">
        <div class="block">
          <h4>Site Pages</h4>
          <ul>
            <li><a href="">My Ads</a></li>
            <li><a href="">Favourite Ads</a></li>
            <li><a href="">Archived Ads</a></li>
            <li><a href="">Pending Ads</a></li>
            <li><a href="">Terms & Conditions</a></li>
          </ul>
        </div>
      </div>
      <!-- Link list -->
      <div class="col-lg-2 col-md-3 offset-md-1 offset-lg-0 col-6 mb-4 mb-md-0">
        <div class="block">
          <h4>Admin Pages</h4>
          <ul>
            <li><a href="">Category</a></li>
            <li><a href="">Single Page</a></li>
            <li><a href="">Store Single</a></li>
            <li><a href="">Single Post</a>
            </li>
            <li><a href="">Blog</a></li>
          </ul>
        </div>
      </div>
      <!-- Promotion -->
      <div class="col-lg-4 col-md-7">
        <!-- App promotion -->
        <div class="block-2 app-promotion">
          <div class="mobile d-flex  align-items-center">
            <a href="">
              <!-- Icon -->
              <img src=" {% static 'images/footer/phone-icon.png' %}" alt="mobile-icon">
            </a>
            <p class="mb-0">Get the E-Voting Mobile App and Save more</p>
          </div>
          <div class="download-btn d-flex my-3">
            <a href=""><img src=" {% static 'images/apps/google-play-store.png' %}" class="img-fluid" alt=""></a>
            <a href="" class=" ml-3"><img src=" {% static 'images/apps/apple-app-store.png' %}" class="img-fluid" alt=""></a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Container End -->
</footer>
<!-- Footer Bottom -->
<footer class="footer-bottom">
  <!-- Container Start -->
  <div class="container">
    <div class="row">
      <div class="col-lg-6 text-center text-lg-left mb-3 mb-lg-0">
        <!-- Copyright -->
        <div class="copyright">
          <p>Copyright &copy; <script>
              var CurrentYear = new Date().getFullYear()
              document.write(CurrentYear)
            </script> <a>Electronic Voting System. All rights reserved.</a></p>
        </div>
      </div>
      <div class="col-lg-6">
        <!-- Social Icons -->
        <ul class="social-media-icons text-center text-lg-right">
          <li><a class="fa fa-facebook" href="https://www.facebook.com/themefisher"></a></li>
          <li><a class="fa fa-twitter" href="https://www.twitter.com/themefisher"></a></li>
          <li><a class="fa fa-pinterest-p" href="https://www.pinterest.com/themefisher"></a></li>
          <li><a class="fa fa-github-alt" href="https://www.github.com/themefisher"></a></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Container End -->
  <!-- To Top -->
  <div class="scroll-top-to">
    <i class="fa fa-angle-up"></i>
  </div>
</footer>

templates/includes/header.html
{% load static %}
<header id="header" class="header align-items-center sticked" >
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <nav class="navbar navbar-expand-lg navbar-light navigation">
          <a class="navbar-brand" href="">
            <img src="{% static 'images/logo.png' %}" alt="" width="180" >
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if 'is_logged_in' not in request.session %}
            <ul class="navbar-nav ml-auto main-nav ">
              {% url 'home:home' as t_url %}
              <li class="nav-item {% if request.path == t_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'home:home' %}">Home</a>
              </li>
              {% url 'home:about_us' as about_us_url %}
              {% url 'home:contact_us' as contact_us_url %}              
              <li class="nav-item dropdown dropdown-slide {% if request.path == about_us_url or request.path == contact_us_url %}active{% endif %}">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#!">Company<span><i class="fa fa-angle-down"></i></span></a>
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item {% if request.path == about_us_url %}active{% endif %}" href="{% url 'home:about_us' %}">About us</a>
                  </li>
                  <li>
                    <a class="dropdown-item {% if request.path == contact_us_url %}active{% endif %}" href="{% url 'home:contact_us' %}">Contact Us</a>
                  </li>
                </ul>
              </li>
     <!-- Elections -->
     {% url 'home:list_elections' as list_elections_url %}
     {% url 'home:list_results' as list_results_url %}
     <li class="nav-item dropdown dropdown-slide {% if request.path == list_elections_url or request.path == list_results_url %}active{% endif %}">
       <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#!">Elections<span><i class="fa fa-angle-down"></i></span></a>
       <ul class="dropdown-menu">
         <li><a class="dropdown-item {% if request.path == list_elections_url %}active{% endif %}" href="{% url 'home:list_elections' %}">Elections</a></li>
         <li><a class="dropdown-item {% if request.path == list_results_url %}active{% endif %}" href="{% url 'home:list_results' %}">Results</a></li>
       </ul>
     </li>
     {% url 'election_officers:sign_in' as election_officers_sign_in_url %}
     {% url 'election_officers:sign_up' as election_officers_sign_up_url %}
              <li class="nav-item dropdown dropdown-slide {% if request.path == election_officers_sign_in_url or request.path == election_officers_sign_up_url %}active{% endif %}">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#!">Officials<span><i class="fa fa-angle-down"></i></span>
                </a>
                <!-- Dropdown list -->
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item {% if request.path == election_officers_sign_in_url %}active{% endif %}" href="{% url 'election_officers:sign_in' %}">Login</a></li>
                  <li><a class="dropdown-item {% if request.path == election_officers_sign_up_url %}active{% endif %}" href="{% url 'election_officers:sign_up' %}">Registration</a></li>
                </ul>
              </li>
              {% url 'candidates:sign_in' as candidates_sign_in_url %}
              {% url 'candidates:sign_up' as candidates_sign_up_url %}
              <li class="nav-item dropdown dropdown-slide {% if request.path == candidates_sign_in_url or request.path == candidates_sign_up_url %}active{% endif %}">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#!">Candidates<span><i class="fa fa-angle-down"></i></span></a>
                <!-- Dropdown list -->
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item {% if request.path == candidates_sign_in_url %}active{% endif %}" href="{% url 'candidates:sign_in' %}">Login</a></li>
                  <li><a class="dropdown-item {% if request.path == candidates_sign_up_url %}active{% endif %}" href="{% url 'candidates:sign_up' %}">Registration</a></li>
                </ul>
              </li>
              </ul>            
              {% url 'voters:sign_up' as voters_sign_up_url %}
              {% url 'voters:sign_in' as voters_sign_in_url %}
              <ul class="navbar-nav ml-auto mt-10">
                  <li class="nav-item">
                      <a class="nav-link login-button" href="{% url 'voters:sign_up' %}">Registration</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link text-white add-button" href="{% url 'voters:sign_in' %}">
                          <i class="fa fa-plus-circle"></i> Login
                      </a>
                  </li>              
              </ul>
            {% endif %}
            {% if 'is_logged_in' in request.session and request.session.user_type == 'voters' %}
            {% url 'voters:dashboard' as voters_dashboard_url %}
            {% url 'voters:edit_profile' as voters_edit_profile_url %}
            {% url 'elections:messages_list' as elections_messages_list_url %}
            {% url 'voters:list_elections' as voters_list_elections_url %}
            <ul class="navbar-nav ml-auto main-nav ">
              <li class="nav-item {% if request.path == voters_dashboard_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'voters:dashboard' %}">Dashboard</a>
              </li>
              <li class="nav-item {% if request.path == voters_edit_profile_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'voters:edit_profile' %}">Edit Profile</a>
              </li>
              <li class="nav-item {% if request.path == elections_messages_list_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'elections:messages_list' %}">Messages</a>
              </li>              
              <li class="nav-item {% if request.path == voters_list_elections_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'voters:list_elections' %}">Election</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'voters:logout' %}"><b>({{ request.session.user_type|capfirst }})</b> logout</a>
              </li>
            </ul>
            {% endif %}
            {% if 'is_logged_in' in request.session and request.session.user_type == 'candidates' %}
            {% url 'candidates:dashboard' as candidates_dashboard_url %}
            {% url 'candidates:edit_profile' as candidates_edit_profile_url %}
            {% url 'elections:messages_list' as elections_messages_list_url %}
            {% url 'candidates:list_voters' as candidates_list_voters_url %}
            {% url 'candidates:list_elections' as candidates_list_elections_url %}
            <ul class="navbar-nav ml-auto main-nav ">
              <li class="nav-item {% if request.path == candidates_dashboard_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'candidates:dashboard' %}">Dashboard</a>
              </li>
              <li class="nav-item {% if request.path == candidates_edit_profile_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'candidates:edit_profile' %}">Edit Profile</a>
              </li>
              <li class="nav-item {% if request.path == elections_messages_list_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'elections:messages_list' %}">Messages</a>
              </li>              
              <li class="nav-item {% if request.path == candidates_list_voters_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'candidates:list_voters' %}">Voters</a>
              </li>
              <li class="nav-item {% if request.path == candidates_list_elections_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'candidates:list_elections' %}">Election</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'candidates:logout' %}"><b>({{ request.session.user_type|capfirst }})</b> logout</a>
              </li>
            </ul>
            {% endif %}
            {% if 'is_logged_in' in request.session and request.session.user_type == 'election_officers' %}
            {% url 'election_officers:dashboard' as eo_dashboard_url %}
            {% url 'elections:messages_list' as eo_messages_list_url %}
            {% url 'election_officers:list_candidates' as eo_list_candidates_url %}
            {% url 'election_officers:list_voters' as eo_list_voters_url %}
            {% url 'elections:list_elections' as eo_list_elections_url %}
            {% url 'election_officers:edit_profile' as eo_edit_profile_url %}
            <ul class="navbar-nav ml-auto main-nav ">
              <li class="nav-item {% if request.path == eo_dashboard_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'election_officers:dashboard' %}">Dashboard</a>
              </li>
              <li class="nav-item {% if request.path == eo_messages_list_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'elections:messages_list' %}">Messages</a>
              </li>
              <li class="nav-item {% if request.path == eo_list_candidates_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'election_officers:list_candidates' %}">Candidates</a>
              </li>              
              <li class="nav-item {% if request.path == eo_list_voters_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'election_officers:list_voters' %}">Voters</a>
              </li>
              <li class="nav-item {% if request.path == eo_list_elections_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'elections:list_elections' %}">Election</a>
              </li>
              <li class="nav-item {% if request.path == eo_edit_profile_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'election_officers:edit_profile' %}">Edit Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'election_officers:logout' %}">logout</a>
              </li>
            </ul>
            {% endif %}
					</div>
				</nav>
			</div>
		</div>
	</div>
</header>