candidates/urls.py
from django.urls import path
from . import views

app_name='candidates'
urlpatterns = [
    path('',views.sign_in,name='sign_in'),    
    path('sign-in',views.sign_in,name='sign_in'),
    path('sign-up',views.sign_up,name='sign_up'),
    path('sign-up-otp/<int:id>',views.sign_up_otp,name='sign_up_otp'),    
    path('signup-check-email',views.signup_check_email,name='signup_check_email'),
    path('signup-check-mobile',views.signup_check_mobile,name='signup_check_mobile'),
    path('signup-check-aadhaar',views.signup_check_aadhaar,name='signup_check_aadhaar'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('edit-profile', views.edit_profile, name='edit_profile'), 
    path('edit-profile-pic', views.edit_profile_pic, name='edit_profile_pic'),
    path('edit-profile-password', views.edit_profile_password, name='edit_profile_password'), 
    path('list-voters', views.list_voters, name='list_voters'),
    path('view-voters/<int:id>', views.view_voters, name='view_voters'),        
    path('list-elections', views.list_elections, name='list_elections'),
    path('view-elections/<int:id>', views.view_elections, name='view_elections'),
    path('delete-elections/<int:id>/<int:id2>', views.delete_elections, name='delete_elections'),    
    path('apply-election-party/<int:id>/<int:party_id>',views.apply_election_party, name='apply_election_party'), 
    path('apply-election-position/<int:id>/<int:position_id>',views.apply_election_position, name='apply_election_position'),         
    path('edit-elections/<int:id>', views.edit_elections, name='edit_elections'),
    path('logout', views.logout, name='logout'),   
]

election_officers/urls.py
from django.urls import path
from . import views

app_name='election_officers'
urlpatterns = [
    path('',views.sign_in,name='sign_in'),    
    path('sign-in',views.sign_in,name='sign_in'),
    path('sign-up',views.sign_up,name='sign_up'),
    path('sign-up-otp/<int:id>',views.sign_up_otp,name='sign_up_otp'),    
    path('signup-check-email',views.signup_check_email,name='signup_check_email'),
    path('signup-check-mobile',views.signup_check_mobile,name='signup_check_mobile'),
    path('signup-check-aadhaar',views.signup_check_aadhaar,name='signup_check_aadhaar'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('edit-profile', views.edit_profile, name='edit_profile'), 
    path('edit-profile-pic', views.edit_profile_pic, name='edit_profile_pic'),
    path('edit-profile-password', views.edit_profile_password, name='edit_profile_password'), 
    path('list-candidates', views.list_candidates, name='list_candidates'), 
    path('list-voters', views.list_voters, name='list_voters'), 
    path('view-candidates/<int:id>', views.view_candidates, name='view_candidates'),
    path('view-voters/<int:id>', views.view_voters, name='view_voters'),
    path('change-user-status/<int:id>', views.change_user_status, name='change_user_status'),
    path('logout', views.logout, name='logout'),   
]

elections/urls.py
from django.urls import path
from . import views

app_name='elections'
urlpatterns = [
    path('messages-list',views.messages_list,name='messages_list'),
    path('messages-view/<int:id>/<int:init_id>/<str:page_type>',views.messages_view,name='messages_view'), 
    path('message-campaign', views.message_campaign, name='message_campaign'),
    path('list-elections', views.list_elections, name='list_elections'),
    path('add-elections', views.add_elections, name='add_elections'),
    path('delete-election/<int:id>', views.delete_election, name='delete_election'),    
    path('edit-elections/<int:id>', views.edit_elections, name='edit_elections'),  
    path('list-election-candidates/<int:id>',views.list_election_candidates, name='list_election_candidates'), 
    path('view-election-candidates/<int:id>/<int:id_2>',views.view_election_candidates, name='view_election_candidates'),   
    path('add-election-candidates/<int:id>/<int:id_2>',views.add_election_candidates, name='add_election_candidates'),
    path('election-parties/<int:id>', views.election_parties_v, name='election_parties'),  
    path('election-position/<int:id>', views.election_position_v, name='election_position'),
    path('election-parties-delete/<int:id>/<int:edit_id>', views.election_parties_delete, name='election_parties_delete'),  
    path('election-position-delete/<int:id>/<int:edit_id> ', views.election_position_delete, name='election_position_delete'),               
    path('delete-election-candidates/<int:id>/<int:id_2>',views.delete_election_candidates, name='delete_election_candidates'),            
]

evoting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin2023/', admin.site.urls),
    path('',include('home.urls',namespace='home'),),        
    path('candidates/',include('candidates.urls',namespace='candidates'),),
    path('election-officers/',include('election_officers.urls',namespace='election_officers'),),
    path('voters/',include('voters.urls',namespace='voters'),), 
    path('elections/',include('elections.urls',namespace='elections')),             
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns = [
    path('',views.home,name='home'),
    path('home',views.home,name='home'),
    path('about-us',views.about_us,name='about_us'),
    path('contact-us',views.contact_us,name='contact_us'),
    path('list-elections',views.list_elections,name='list_elections'),
    path('view-elections',views.view_elections,name='view_elections'),    
    path('list-results',views.list_results,name='list_results'),
    path('view-results/<int:id>',views.view_results,name='view_results'),         
]

candidates/models.py
from django.db import models

# Create your models here.

candidates/views.py
import base64, random
from Crypto.Cipher import AES
from Crypto.Util.Padding import pad, unpad
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from .models import *
from elections.models import user_registration, elections, election_candidates, election_votes, messages_contain
from django.db.models import Avg, Count
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse

# Define the AES256 encryption and decryption functions
def encrypt_AES256(plaintext):
    key = settings.SECRET_KEY
    iv = b'1234567890123456' # Initialization vector
    cipher = AES.new(key, AES.MODE_CBC, iv)
    ciphertext = cipher.encrypt(pad(plaintext.encode(), AES.block_size))
    return base64.b64encode(ciphertext).decode()

def decrypt_AES256(ciphertext):
    key = settings.SECRET_KEY
    iv = b'1234567890123456' # Initialization vector
    ciphertext = base64.b64decode(ciphertext.encode())
    cipher = AES.new(key, AES.MODE_CBC, iv)
    plaintext = unpad(cipher.decrypt(ciphertext), AES.block_size)
    return plaintext.decode()

def sign_in(request):
    if request.method == 'POST':
            data_record = request.POST
            if user_registration.objects.filter(mobile_number=data_record['mobile_number'],password=encrypt_AES256(data_record['password']),user_type='candidates',otp_status='yes'):
                user_details = user_registration.objects.get(mobile_number=data_record['mobile_number'],password=encrypt_AES256(data_record['password']),user_type='candidates',otp_status='yes')
                if user_details.status == 'active':
                    request.session['is_logged_in'] = True
                    request.session['user_type'] = 'candidates'                    
                    request.session['user_id'] = user_details.unique_id   
                    request.session['first_name'] = user_details.first_name
                    request.session['last_name'] = user_details.last_name                                     
                    request.session['email_address'] = user_details.email_address
                    request.session['mobile_number'] = user_details.mobile_number
                    request.session['aadhaar_number'] = user_details.aadhaar_number
                    return redirect(reverse('candidates:dashboard'))
                else:
                    messages.error(request, 'User is suspended. Contact the admin!')
                    return redirect(reverse('candidates:sign_in'))
            else:
                messages.error(request, 'Invalid credentials!')
                return redirect(reverse('candidates:sign_in'))
    return render(request, 'candidates/login.html')

def sign_up(request):
    if request.method == 'POST':
        data_record = request.POST

        # if condition to check and remove leftover registrations
        if user_registration.objects.filter(email_address=data_record['email_address'],user_type='candidates',otp_status='no').count() > 0:
            user_registration.objects.filter(email_address=data_record['email_address'],user_type='candidates',otp_status='no').delete()
        elif user_registration.objects.filter(mobile_number=data_record['mobile_number'],user_type='candidates',otp_status='no').count() > 0:
            user_registration.objects.filter(mobile_number=data_record['mobile_number'],user_type='candidates',otp_status='no').delete()
        elif user_registration.objects.filter(aadhaar_number=data_record['aadhaar_number'],user_type='candidates',otp_status='no').count() > 0:
            user_registration.objects.filter(aadhaar_number=data_record['aadhaar_number'],user_type='candidates',otp_status='no').delete()

        if user_registration.objects.filter(email_address=data_record['email_address'],user_type='candidates',otp_status='yes'):
            messages.error(request, 'Email already exists! Please try again!')
            return redirect(reverse('candidates:sign_up'))
        elif user_registration.objects.filter(mobile_number=data_record['mobile_number'],user_type='candidates',otp_status='yes'):
            messages.error(request, 'Mobile number already exists! Please try again!')
            return redirect(reverse('candidates:sign_up'))
        elif user_registration.objects.filter(aadhaar_number=data_record['aadhaar_number'],user_type='candidates',otp_status='yes'):
            messages.error(request, 'Aadhaar number already exists! Please try again!')
            return redirect(reverse('candidates:sign_up'))        
        else:
            profile_photo = request.FILES['profile_photo']
            folder = 'candidates' # subfolder name
            fs = FileSystemStorage(location=f'media/{folder}')
            file_name = fs.save(profile_photo.name, profile_photo)
            signup = user_registration(
                user_type = 'candidates',
                first_name = data_record['first_name'],
                last_name = data_record['last_name'],
                mobile_number = data_record['mobile_number'],
                email_address = data_record['email_address'],
                password = encrypt_AES256(data_record['password']),
                address_line_1 = data_record['address_line_1'],
                address_line_2 = data_record['address_line_2'],
                district = data_record['district'],
                state = data_record['state'],
                pin_code = data_record['pin_code'],
                aadhaar_number = data_record['aadhaar_number'],                
                profile_photo = f'{folder}/{file_name}',
                status='pending',
            )            
            signup.save()
            last_insert_id = signup.unique_id            
            messages.success(request, 'candidates registration added! Complete otp validation..')
            return redirect(reverse('candidates:sign_up_otp', kwargs={'id': last_insert_id}))
    context = {}
    return render(request, 'candidates/registration.html', context)

def sign_up_otp(request, id):
    if request.method == 'POST':
            data_record = request.POST
            print(data_record['otp_number'])
            if data_record['otp_number'] == '123321':
                userdata = user_registration.objects.get(unique_id=id)
                userdata.otp_status = 'yes'
                userdata.save() 
                messages.error(request, 'Candidates registered successfully! Sign in here.')
                return redirect(reverse('candidates:sign_in'))                  
            else:
                messages.error(request, 'Invalid Otp! Please try again with correct otp')
                return redirect(reverse('candidates:sign_up_otp'))    
    return render(request, 'candidates/registration-otp.html')    

def signup_check_email(request):
    flag = 0
    if 'is_logged_in' in request.session and 'user_type' in request.session and request.session['user_type'] == 'candidates':
        flag = True
    else:
        flag = False
    if request.method == 'POST':
        data_record = request.POST
        # Check if the email exists in the database
        if flag:
            temp_value = user_registration.objects.filter(email_address=data_record['email_a'],user_type='candidates',otp_status='yes').exclude(email_address=request.session['email_address']).exists()
        else:
            temp_value = user_registration.objects.filter(email_address=data_record['email_a'],user_type='candidates',otp_status='yes').exists()   
        if temp_value:
            response_data = {'exists': True}
        else:
            response_data = {'exists': False}
        # Return the result as a JSON response
    else:
        response_data = {'exists': True}    
    return JsonResponse(response_data)

def signup_check_mobile(request):
    flag = 0
    if 'is_logged_in' in request.session and 'user_type' in request.session and request.session['user_type'] == 'candidates':
        flag = True
    else:
        flag = False    
    if request.method == 'POST':
        data_record = request.POST
        # Check if the phone number exists in the database
        if flag:
            temp_value = user_registration.objects.filter(mobile_number=data_record['mobile_number'],user_type='candidates',otp_status='yes').exclude(mobile_number=request.session['mobile_number']).exists()
        else:
            temp_value = user_registration.objects.filter(mobile_number=data_record['mobile_number'],user_type='candidates',otp_status='yes').exists()   
        if temp_value:        
            response_data = {'exists': True}
        else:
            response_data = {'exists': False}
        # Return the result as a JSON response
    else:
        response_data = {'exists': True}    
    return JsonResponse(response_data)

def signup_check_aadhaar(request):
    flag = 0
    if 'is_logged_in' in request.session and 'user_type' in request.session and request.session['user_type'] == 'candidates':
        flag = True
    else:
        flag = False    
    if request.method == 'POST':
        data_record = request.POST
        # Check if the phone number exists in the database
        if flag:
            temp_value = user_registration.objects.filter(aadhaar_number=data_record['aadhaar_number'],user_type='candidates',otp_status='yes').exclude(aadhaar_number=request.session['aadhaar_number']).exists()
        else:
            temp_value = user_registration.objects.filter(aadhaar_number=data_record['aadhaar_number'],user_type='candidates',otp_status='yes').exists()   
        if temp_value:
            response_data = {'exists': True}
        else:
            response_data = {'exists': False}
        # Return the result as a JSON response
    else:
        response_data = {'exists': True}    
    return JsonResponse(response_data)

def logout(request):
    del request.session['is_logged_in']

templates/candidates/edit-profile.html
{% extends 'layout.html' %}
{% block title %}
eVoting
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
{% endblock %}
<!-- custom css end-->
{% block content %}
<section class="page-title">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-md-2 text-center">
				<!-- Title text -->
			</div>
		</div>
	</div>
	<!-- Container End -->
</section>
<section class="dashboard section">
  <!-- Container Start -->
  <div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
          <div class="section-title">
            <h2>Edit Profile</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">
            {% if messages %}
            <ul class="messages text-center">
            {% for message in messages %}
             <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
             {% endfor %}
             </ul>
             {% endif %}
      </div>
      </div>
    <!-- Row Start -->
    <div class="row">
      <div class="col-lg-4">
        <div class="sidebar">
          <!-- User Widget -->
          <div class="widget user-dashboard-profile">
            <!-- User Image -->
            <div class="profile-thumb">
              <img src="{{ userdata.profile_photo.url }}" alt="" class="rounded-circle">
            </div>
            <!-- User Name -->
            <h5 class="text-center">{{ userdata.first_name }} {{ userdata.last_name }}</h5>
            <p>Joined {{ userdata.date_added }}</p>
          </div>

          
          <div class="widget personal-info">
            <h3 class="widget-header user">Edit Personal Information</h3>
            <form action="{% url 'candidates:edit_profile_pic' %}" id="myform1" method="post" enctype="multipart/form-data">
              {% csrf_token %}
                <!-- File chooser -->
                <div class="form-group choose-file d-inline-flex">
                    <i class="fa fa-user text-center px-3"></i>
                    <input type="file" class="form-control-file mt-2 pt-1" name="profile_photo" id="profile_photo" >
                 </div>
                 <div class="col-md-12 error-msg"></div>
                <!-- Submit button -->
                <button class="btn btn-transparent" type="submit">Save My Changes</button>
            </form>
        </div>   
          <!-- Dashboard Links -->

          

        </div>
      </div>
      <div class="col-lg-8">
        <!-- Edit Personal Info -->
        <div class="row">
            <div class="col-lg-6 col-md-6">
                <div class="widget personal-info">
                    <h3 class="widget-header user">Edit Personal Information</h3>
                    <form action="{% url 'candidates:edit_profile' %}" id="myform2" method="post" role="form" >
                      {% csrf_token %}
                      <!-- First Name -->
                      <div class="form-group">
                          <label for="first-name">First Name</label>
                          <input type="text" class="form-control" name="first_name" id="first_name" placeholder="" value="{{ userdata.first_name }}" >
                      </div>
                      <!-- Last Name -->
                      <div class="form-group">
                          <label for="last-name">Last Name</label>
                          <input type="text" class="form-control" name="last_name" id="last_name" placeholder="" value="{{ userdata.last_name }}" >
                      </div>
                      <!-- Email Address -->
                      <div class="form-group">
                          <label for="email-address">Email Address</label>
                          <input type="email" class="form-control" name="email_address" id="email_address" placeholder="" value="{{ userdata.email_address }}" >
                      </div>
                      <!-- Mobile Number -->
                      <div class="form-group">
                          <label for="mobile-number">Mobile Number</label>
                          <input type="number" class="form-control" name="mobile_number" id="mobile_number" placeholder="" value="{{ userdata.mobile_number }}" >
                      </div>
                      <!-- Aadhaar Number -->
                      <div class="form-group">
                          <label for="aadhaar-number">Aadhaar Number</label>
                          <input type="text" class="form-control" name="aadhaar_number" id="aadhaar_number" placeholder="" value="{{ userdata.aadhaar_number }}" >
                      </div>
                      <!-- Address Line 1 -->
                      <div class="form-group">
                          <label for="address-line-1">Address Line 1</label>
                          <input type="text" class="form-control" name="address_line_1" id="address_line_1" placeholder="" value="{{ userdata.address_line_1 }}" >
                      </div>
                      <!-- Address Line 2 -->
                      <div class="form-group">
                          <label for="address-line-2">Address Line 2</label>
                          <input type="text" class="form-control" name="address_line_2" id="address_line_2" placeholder="" value="{{ userdata.address_line_2 }}" >
                      </div>
                      <!-- District -->
                      <div class="form-group">
                          <label for="district">District</label>
                          <input type="text" class="form-control" name="district" id="district" placeholder="" value="{{ userdata.district }}" >
                      </div>
                      <!-- State -->
                      <div class="form-group">
                          <label for="state">State</label>
                          <input type="text" class="form-control" name="state" id="state" placeholder="" value="{{ userdata.state }}" >
                      </div>
                      <!-- Pin Code -->
                      <div class="form-group">
                          <label for="pin-code">Pin Code</label>
                          <input type="text" class="form-control" name="pin_code" id="pin_code" placeholder="" value="{{ userdata.pin_code }}" >                  
                        </div>
                        <!-- Submit button -->
                        <button class="btn btn-transparent">Save My Changes</button>
                    </form>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <!-- Change Password -->
            <div class="widget change-password">
                <h3 class="widget-header user">Edit Password</h3>
                <form action="{% url 'candidates:edit_profile_password' %}" id="myform3" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                    <!-- Current Password -->
                    <div class="form-group">
                        <label for="current-password">Current Password</label>
                        <input type="password" class="form-control" name="old_password" id="old_password" >
                    </div>
                    <!-- New Password -->
                    <div class="form-group">
                        <label for="new-password">New Password</label>
                        <input type="password" class="form-control" name="password" id="password" >
                    </div>
                    <!-- Confirm New Password -->
                    <div class="form-group">
                        <label for="confirm-password">Confirm New Password</label>
                        <input type="password" class="form-control" name="confirm_password" id="confirm_password" >
                    </div>
                    <!-- Submit Button -->
                    <button type="submit" class="btn btn-transparent">Change Password</button>
                </form>
            </div>
            </div>
            
        </div>
    </div>
</div>
    </div>
    <!-- Row End -->
  </div>
  <!-- Container End -->
</section>

{% endblock %}
<!-- custom js -->
{% block js %}
<script src="{% static 'plugins/jquery-validate/jquery.validate.min.js' %}" defer></script>
<script src="{% static 'plugins/jquery-validate/additional-methods.min.js' %}" defer></script>
<script>
$(document).ready(function(){

$( "#myform1" ).validate({
    ignore: [],
    rules: {
    profile_photo: {
			required: true,
			extension:'png,jpg,jpeg',
		}, 
  } , 
  errorPlacement: function(error, element) {
      // Insert error message after the input field
      error.appendTo('.error-msg');
    },
  }); 

     $.validator.addMethod("checkPhoneExist", function(value, element) {
      var exists = false;
      $.ajax({
        url: "{% url 'candidates:signup_check_mobile' %}",
        method: "POST",
        data: {
          mobile_number: value,
          csrfmiddlewaretoken: '{{ csrf_token }}',
        },
        async: false,
        success: function(data) {
          exists = data.exists;
        }
      });
      return !exists;
    }, "This mobile number already exists in the database."); 

    $.validator.addMethod("checkEmailExist", function(value, element) {
      var exists = false;
      $.ajax({
        url: "{% url 'candidates:signup_check_email' %}",
        method: "POST",
        data: {
          email_a: value,
          csrfmiddlewaretoken: '{{ csrf_token }}',
        },
        async: false,
        success: function(data) {
          exists = data.exists;
        }
      });
      return !exists;
    }, "This email address already exists in the database.");     

    $.validator.addMethod("checkAadhaarExist", function(value, element) {
      var exists = false;
      $.ajax({
        url: "{% url 'candidates:signup_check_aadhaar' %}",
        method: "POST",
        data: {
          aadhaar_number: value,
          csrfmiddlewaretoken: '{{ csrf_token }}',
        },
        async: false,
        success: function(data) {
          exists = data.exists;
        }
      });
      return !exists;
    }, "This aadhaar number already exists in the database.");  
  
    $("#myform2").validate({
  rules: {
    first_name: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    last_name: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    mobile_number: {
      required: true,
      digits: true,
      minlength: 10,
      maxlength: 10,
      checkPhoneExist: true  
    },
    email_address: {
      required: true,
      email: true,
      minlength: 8,
      maxlength: 255,
      checkEmailExist: true   
    },
    password: {
      required: true,
      minlength: 5,
      maxlength: 35,
    },
    confirm_password: {
      required: true,
      minlength: 5,
      maxlength: 35,
      equalTo: "#password"
    },
    address_line_1: {
      required: true,
      minlength: 5,
      maxlength: 255
    },    
    address_line_2: {
      required: false,
      maxlength: 255
    },
    district: {
      required: true,
      minlength: 2,
      maxlength: 255
    },
    state: {
      required: true,
      minlength: 2,
      maxlength: 255
    },
    pin_code: {
      required: true,
      digits: true,
      minlength: 6,
      maxlength: 6
    },
    aadhaar_number: {
      required: true,
      minlength: 12,
      maxlength: 12,
      digits: true,
      checkAadhaarExist: true
    }
  },
  messages: {
    first_name: "Please enter your first name",
    last_name: "Please enter your last name",
    mobile_number: {
      required: "Please enter your mobile number",
      minlength: "Your mobile number must be at least 10 digits long"
    },
    email_address: {
      required: "Please enter your email address",
      email: "Please enter a valid email address"
    },
    password: {
      required: "Please enter a password",
      minlength: "Your password must be at least 8 characters long"
    },
    confirm_password: {
      required: "Please confirm your password",
      minlength: "Your password must be at least 8 characters long",
      equalTo: "Your passwords do not match"
    },
    address_line_1: "Please enter your address",
    district: "Please enter your district",
    state: "Please enter your state",
    pin_code: {
      required: "Please enter your pin code",
      minlength: "Your pin code must be at least 6 digits long"
    },
    profile_photo: "Please upload a profile photo",
    aadhaar_number: {
      required: "Please enter your Aadhaar number",
      minlength: "Your Aadhaar number must be 12 digits long",
      maxlength: "Your Aadhaar number must be 12 digits long",
      digits: "Your Aadhaar number must contain only digits"
    }
  }
});

  $( "#myform3" ).validate({
  ignore: [],
  rules: {
  old_password: {
    required: true,
    minlength: 5,
    maxlength: 35,
  },      
  password: {
    required: true,
    minlength: 5,
    maxlength: 35,
  },
  confirm_password: {
    required: true,
    minlength: 5,
    maxlength: 35,
    equalTo: "#password"
  },
  }
  });  

}); 
</script>
{% endblock %}
<!-- custom js end-->